name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{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}}
          GIST_ID: ${{66539b2ca8f20f19364cc0dbb937214f}}
          TIMEZONE: ${{Asia/Seoul}}
